name: dev_2_장고_템플릿_기반_깃허브_액션스_추가_및_배포-2025-06-16

on:
  push:
    branches:
      - dev_2_장고_템플릿_기반_깃허브_액션스_추가_및_배포-2025-06-16

jobs:
  dev_2_deploy:
    name: Deploy to the EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create remote directory on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            sudo rm -rf /home/ubuntu/django-react-hjs-distribute
            mkdir -p /home/ubuntu/django-react-hjs-distribute